### PR TITLE
Make findFilesInDir use pathtype.

### LINKED ISSUE #288: Finish migrating to `pathtype` library.
The migration to `pathtype` has been overall a pleasant one—it makes functions much more indicative of their purpose, and it’s caught some bugs (though not serious ones). Right now we’re an uneasy hybrid of `pathtype` solutions and `FilePath`; we should move off of the latter completely. This involves overhauling `Semantic.CLI` to use `pathtype`; the [documentation](http://hackage.haskell.org/package/pathtype-0.8.1) provides a recipe to make `optparse-applicative` parsers do the right thing (respecting the path semantics; i.e., if we tell a parser to expect an absolute path, the parser will fail unless said path is actually absolute.)

### PR DESCRIPTION
**Pull request by patrickt**
There are more general refactors that have to happen before we can zap #288, but this gets us some of the way there, and provide nice type guarantees.

### CODE REVIEW

File: src/Semantic/IO.hs [hunk 1]
```diff
@@ -12,20 +12,22 @@ import           System.Directory (doesDirectoryExist)
...
 import           System.FilePath
+import qualified System.Path as Path
+import qualified System.Path.PartClass as Path.PartClass
 
 isDirectory :: MonadIO m => FilePath -> m Bool
 isDirectory path = liftIO (doesDirectoryExist path)
 
 -- Recursively find files in a directory.
-findFilesInDir :: MonadIO m => FilePath -> [String] -> [FilePath] -> m [FilePath]
+findFilesInDir :: (Path.PartClass.AbsRel ar, MonadIO m) => Path.Dir ar -> [String] -> [Path.Dir ar] -> m [Path.File ar]
```
Comment (patrickt) [inline src/Semantic/IO.hs]: If you pass in an `AbsDIr`, you will get `AbsFile`s out. If you pass in a `RelDir`, you will get `RelFile`s out. And so on.

File: src/Data/Blob.hs [hunk 2]
```diff
@@ -44,12 +45,12 @@ data File = File
   , fileLanguage :: Language
   } deriving (Show, Eq, Generic)
 
--- | Prefer 'fileForRelPath' if at all possible.
+-- | Prefer 'fileForTypedPath' if at all possible.
 fileForPath :: FilePath  -> File
```
Comment (patrickt) [inline src/Data/Blob.hs]: We can’t _quite_ kill this yet because there are still some CLI actions that create a `File` even though the `FilePath` they wrap is a directory. This is a wart, yes, but the changes required fall outside of the purview of this patch, so I’m leaving it for now.

File: src/Data/Blob.hs [hunk 3]
```diff
@@ -44,12 +45,12 @@ data File = File
...
 fileForPath p = File p (languageForFilePath p)
 
-fileForRelPath :: Path.RelFile -> File
-fileForRelPath = fileForPath . Path.toString
+fileForTypedPath :: Path.PartClass.AbsRel ar => Path.File ar -> File
+fileForTypedPath = fileForPath . Path.toString
```
Comment (patrickt) [inline src/Data/Blob.hs]: This now admits a more general type—any of `Path.AbsFile`, `Path.RelFile`, or `Path.AbsRelFile` will suffice. As such, I changed its name.

File: src/Data/Blob/IO.hs [hunk 4]
```diff
@@ -40,7 +40,7 @@ readBlobFromFile' file = do
 -- | Read all blobs in the directory with Language.supportedExts.
 readBlobsFromDir :: MonadIO m => Path.AbsRelDir -> m [Blob]
 readBlobsFromDir path = liftIO . fmap catMaybes $
-  findFilesInDir (Path.toString path) supportedExts mempty >>= Async.mapConcurrently (readBlobFromFile . fileForPath)
+  findFilesInDir path supportedExts mempty >>= Async.mapConcurrently (readBlobFromFile . fileForTypedPath)
```
Comment (patrickt) [inline src/Data/Blob/IO.hs]: 😄

File: src/Data/Project.hs [hunk 5]
```diff
@@ -41,9 +42,9 @@ readProjectFromPaths maybeRoot path lang excludeDirs = do
       then fromMaybe path maybeRoot
       else fromMaybe (takeDirectory path) maybeRoot
 
-  paths <- liftIO $ findFilesInDir rootDir exts excludeDirs
+  paths <- liftIO $ findFilesInDir (Path.absRel rootDir) exts (fmap Path.absRel excludeDirs)
```
Comment (patrickt) [inline src/Data/Project.hs]: These calls will go away when `Project` and `File` have typed members.

File: src/Semantic/Resolution.hs [hunk 6]
```diff
@@ -20,12 +20,13 @@ import           Prologue
...
 import           System.FilePath.Posix
+import qualified System.Path as Path
 
 
 nodeJSResolutionMap :: (Member Files sig, Carrier sig m, MonadIO m) => FilePath -> Text -> [FilePath] -> m (Map FilePath FilePath)
 nodeJSResolutionMap rootDir prop excludeDirs = do
-  files <- findFiles rootDir [".json"] excludeDirs
-  let packageFiles = fileForPath <$> filter ((==) "package.json" . takeFileName) files
+  files <- findFiles (Path.absRel rootDir) [".json"] (fmap Path.absRel excludeDirs)
+  let packageFiles = fileForTypedPath <$> filter ((==) (Path.relFile "package.json") . Path.takeFileName) files
```
Comment (patrickt) [inline src/Semantic/Resolution.hs]: I will spruce `nodeJSResolutionMap` up in a subsequent pass.
