### PR TITLE
Re-enable `semantic parse --json` output.

### LINKED ISSUE #471: Enable JSON-dumping of precise ASTs.
**Semantic version**: [0.7.0.0](https://github.com/github/semantic/releases/tag/0.7.0.0)
**Input file**: [EurekaServiceDiscovery.java](https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-eureka/src/main/java/org/apache/dubbo/registry/eureka/EurekaServiceDiscovery.java) of Apache dubbo
**Command**: `semantic parse --json EurekaServiceDiscovery.java`
**Error logs**: 
~~~
[01:12:42]  WAR{"trees":[{"tree":{"term":"Error","errorActual":"ParseError","errorCallStack":[{"startLine":159,"module":"Language.Java.Assignment","package":"semantic-0.7.0.0-inplace","site":"parseError","file":"src/Language/Java/Assignment.hs","startColumn":128,"endColumn":138}],"errorChildren":[],"errorExpected":[],"sourceRange":[0,7602],"sourceSpan":{"start":[1,1],"end":[188,51]}},"path":"EurekaServiceDiscovery.java","language":"Java"}]}
N EurekaServiceDiscovery.java:1:1-188:51: error: expected end of input nodes, but got ParseError
1: /*
   ^...

 task=parse github_request_id=- github_is_public=False path=EurekaServiceDiscovery.java language=Java
~~~

But `tree-sitter` works fine to parse this file. Maybe there are some bugs with semantic to parse Java, someone help me to fix this please!

### PR DESCRIPTION
**Pull request by patrickt**
When we switched away from alacarte syntax, we lost the `--json`
option for AST output. However, the majority of the needed code was
already implemented by @aymannadeem, so all we had to do was have the
syntax types opt into the `MarshalJSON` API, and to define the
boilerplate needed to plug it into the `Serialize` interface.

Fixes #471.

### CODE REVIEW

File: WORKSPACE [hunk 1]
```diff
@@ -48,6 +48,10 @@ rules_haskell_toolchains(
     version = "8.8.3",
 )
 
+# Enable GHC persistent worker mode, if that's your bag.
+load("@rules_haskell//tools:repositories.bzl", "rules_haskell_worker_dependencies")
+
+rules_haskell_worker_dependencies()
```
Comment (patrickt) [inline WORKSPACE:54]: This block allows Bazel to run a GHC instance in the background and delegate build requests to it. This makes a lot of IDE’s more responsive. You can enable it by putting this in your `.bazelrc.local`:

```
build --worker_sandboxing=yes
build --define use_worker=True
```

File: semantic-codeql/src/Language/CodeQL.hs [hunk 2]
```diff
@@ -1,9 +1,12 @@
+{-# LANGUAGE GeneralizedNewtypeDeriving #-}
+{-# OPTIONS_GHC -freduction-depth=0 #-}
```
Comment (patrickt) [inline semantic-codeql/src/Language/CodeQL.hs:2]: The datatypes here are sufficiently nested and gnarly that GHC has issues proving that typechecking will terminate. We already had this fix deployed for TSX/TypeScript, so I don’t consider it particularly evil.

File: semantic/src/Semantic/Api/Terms.hs [hunk 3]
```diff
@@ -69,74 +71,95 @@ showTermParsers = preciseParsers
 class ShowTerm term where
   showTerm :: (Has (Reader Config) sig m) => term Loc -> m Builder
 
-instance (ShowTermBy term) => ShowTerm term where
-  showTerm = showTermBy @term
```
Comment (patrickt) [inline semantic/src/Semantic/Api/Terms.hs:73]: We used to have two typeclasses per serialization interface, due to alacarte/precise syntax differences. Due to type weirdness, we still need one, but I removed the other `TermBy` classes.

File: semantic/src/Serializing/Format.hs [hunk 4]
```diff
@@ -16,19 +19,22 @@ import Data.ProtoLens.Encoding as Proto
...
 import Language.Haskell.HsColour
 import Language.Haskell.HsColour.Colourise
+import Source.Loc
 import Text.Show.Pretty
 
 data Format input where
-  DOT         :: (Ord vertex, ToGraph graph, ToVertex graph ~ vertex) => Style vertex Builder -> Format graph
-  JSON        :: ToJSON input                                         =>                         Format input
-  Show        :: Show input                                           =>                         Format input
-  Proto       :: Message input                                        =>                         Format input
```
Comment (patrickt) [inline semantic/src/Serializing/Format.hs:25]: This looks absurd and would have generated a gory diff anyway, so I hit it with `ormolu`.

**Comment by ce-bo** [comment]
@patrickt I am not sure if `--json` is a stable flag. If so, the documentation should be updated.
